# Generated by Django 3.2.19 on 2023-06-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='capacity',
        ),
        migrations.AddField(
            model_name='reservation',
            name='guests',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
