# Generated by Django 3.2.19 on 2023-06-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20230607_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guests',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
